
import type { Config } from './types';

export const FONT_FACES = [
  'Arial',
  'Verdana',
  'Georgia',
  'Roboto',
  'Lato',
  'Montserrat',
  'Noto Sans JP',
  'Meiryo',
  'MS Gothic',
  'MS Mincho',
];

export const DEFAULT_CONFIG: Config = {
  FONTS: {
    family: 'Arial',
    fontSizeMultiplier: 1,
    sizes: {
      title: 45,
      date: 16,
      sectionTitle: 38,
      contentTitle: 28,
      subhead: 18,
      body: 14,
      footer: 9,
      chip: 11,
      laneTitle: 13,
      small: 10,
      processStep: 14,
      axis: 12,
      ghostNum: 180,
    },
  },
  COLORS: {
    primary_blue: '#4285F4',
    google_red: '#EA4335',
    google_yellow: '#FBBC04',
    google_green: '#34A853',
    text_primary: '#333333',
    background_white: '#FFFFFF',
    background_gray: '#f8f9fa',
    faint_gray: '#e8eaed',
    lane_title_bg: '#f5f5f3',
    lane_border: '#dadce0',
    card_bg: '#ffffff',
    card_border: '#dadce0',
    neutral_gray: '#9e9e9e',
    ghost_gray: '#efefed',
  },
  LOGOS: {
    header: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1024px-Google_2015_logo.svg.png',
    closing: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1024px-Google_2015_logo.svg.png',
  },
  FOOTER_TEXT: `© ${new Date().getFullYear()} あなたの組織名`,
};

export const THEMES = [
  {
    name: 'Googleオリジナル',
    colors: DEFAULT_CONFIG.COLORS,
  },
  {
    name: 'モダンダーク',
    colors: {
      primary_blue: '#61AFFE',
      google_red: '#F28B82',
      google_yellow: '#FDD663',
      google_green: '#81C995',
      text_primary: '#E8EAED',
      background_white: '#202124',
      background_gray: '#292A2D',
      faint_gray: '#3C4043',
      lane_title_bg: '#3C4043',
      lane_border: '#5F6368',
      card_bg: '#292A2D',
      card_border: '#5F6368',
      neutral_gray: '#9AA0A6',
      ghost_gray: '#3C4043',
    },
  },
  {
    name: 'プロフェッショナルブルー',
    colors: {
        primary_blue: '#0D47A1',
        google_red: '#D32F2F',
        google_yellow: '#FBC02D',
        google_green: '#388E3C',
        text_primary: '#212121',
        background_white: '#FFFFFF',
        background_gray: '#F5F5F5',
        faint_gray: '#E0E0E0',
        lane_title_bg: '#E3F2FD',
        lane_border: '#BDBDBD',
        card_bg: '#FFFFFF',
        card_border: '#BDBDBD',
        neutral_gray: '#757575',
        ghost_gray: '#ECEFF1',
    },
  },
  {
    name: '洗練ネイビー＆ゴールド',
    colors: {
      primary_blue: '#0A2B4C',
      google_red: '#C94D4D',
      google_yellow: '#D4A24E',
      google_green: '#4E8081',
      text_primary: '#212121',
      background_white: '#FFFFFF',
      background_gray: '#F4F6F8',
      faint_gray: '#EAECEF',
      lane_title_bg: '#E7EEF5',
      lane_border: '#C5D2DE',
      card_bg: '#FFFFFF',
      card_border: '#C5D2DE',
      neutral_gray: '#6C757D',
      ghost_gray: '#E7EEF5',
    },
  },
  {
    name: 'エネルギッシュオレンジ',
    colors: {
      primary_blue: '#D95F43',
      google_red: '#D95F43',
      google_yellow: '#F3C868',
      google_green: '#5A94A5',
      text_primary: '#333333',
      background_white: '#FCFCFC',
      background_gray: '#F0F0F0',
      faint_gray: '#E0E0E0',
      lane_title_bg: '#FAECE7',
      lane_border: '#D1D1D1',
      card_bg: '#FFFFFF',
      card_border: '#D1D1D1',
      neutral_gray: '#828282',
      ghost_gray: '#EAEAEA',
    },
  },
  {
    name: '信頼グリーン＆アース',
    colors: {
      primary_blue: '#2E6B5D',
      google_red: '#A95C48',
      google_yellow: '#E3B873',
      google_green: '#2E6B5D',
      text_primary: '#4A4A4A',
      background_white: '#FDFBF5',
      background_gray: '#F5F2EA',
      faint_gray: '#E9E5DC',
      lane_title_bg: '#EAF0EE',
      lane_border: '#D3CFC2',
      card_bg: '#FDFBF5',
      card_border: '#D3CFC2',
      neutral_gray: '#8B857A',
      ghost_gray: '#F0ECE4',
    },
  },
  {
    name: 'クリエイティブパープル',
    colors: {
      primary_blue: '#5D407A',
      google_red: '#E91E63',
      google_yellow: '#FFC107',
      google_green: '#009688',
      text_primary: '#333333',
      background_white: '#FFFFFF',
      background_gray: '#F2F0F5',
      faint_gray: '#E5E0EB',
      lane_title_bg: '#EDE7F6',
      lane_border: '#D1C4E9',
      card_bg: '#FFFFFF',
      card_border: '#D1C4E9',
      neutral_gray: '#757575',
      ghost_gray: '#F0EDF3',
    },
  },
  {
    name: 'クラシックワイン',
    colors: {
      primary_blue: '#880E4F',
      google_red: '#C62828',
      google_yellow: '#FFEB3B',
      google_green: '#4CAF50',
      text_primary: '#212121',
      background_white: '#FFF8E1',
      background_gray: '#F5F2E9',
      faint_gray: '#EFEBE2',
      lane_title_bg: '#FCE4EC',
      lane_border: '#E0E0E0',
      card_bg: '#FFF8E1',
      card_border: '#E0E0E0',
      neutral_gray: '#616161',
      ghost_gray: '#F5F3ED',
    },
  },
];